#AMAURY MARIO RIBEIRO NETO

tokens = {
  "program":  "PROGRAM",
  "begin":	  "BEGIN",
  "end":    	"END",
  "var":    	"VAR",
  "integer":  "INTEGER",
  "boolean":  "BOOLEAN",
  "real":     "REAL",
  "string":   "STRING",
  "if":       "IF",
  "then":     "THEN",
  "while":    "WHILE",
  "do":       "DO",
  "read":     "READ",
  "print":    "PRINT",
  ":":        "COLON",
  "true":     "TRUE",
  "false":    "FALSE",
  "(":        "LBRACKET",
  ")":        "RBRACKET",
  ",":        "COMMA",
  ";":        "PCOMMA",
  ":=":       "ATTR",
  "==":       "EQ",
  "!=":       "NE",
  "<":        "LT",
  "<=":       "LE",
  ">":        "GT",
  ">=":       "GE",
  "+":        "PLUS",
  "-":        "MINUS",
  "*":        "MULT",
  "/":        "DIV",
}
